# Generated by Django 4.0.4 on 2022-05-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name']},
        ),
        migrations.AddField(
            model_name='photo',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
