# Generated by Django 4.0.4 on 2022-05-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_user_options_photo_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_image',
            field=models.ImageField(blank=True, upload_to='index/'),
        ),
    ]
